local codes = {
    "Sub2CodeNex77k",
    "RELEASE",
    "SorryForDelay",
    "TyFor2kFav",
    "FinalDelay",
    "FreeNami",
    "3219872",
    "Async",
    "Shock",
    "here", --
    "ToadBoi120k",
    "DISGUISED",
    "D1SGUISED",
    "Sub2KingLuffy",
    "Sub2HotSauceHan",
    "BlamTopSecretCodeWontWorkIfNotSubbed",
    "GoalReached",
    "neelsTV",
    "BlamsSecret1MillionUniquePlayerCode",
    "Shutdown",
    "Fixes",
    "FminusMicSecretCodeMustBeSubbedToWorkLOL",
    "BlamsOP5MillionVisitsRerollCodeMustBeSubbedToWorkLOL",
    "Update1Hype",
    "BlamsAndShocksNightmare100kMemberReRollCodeTrySubscribingToBlamSpotOnYTAndFollowingFr_ShockOnTwitterIfItDoesntWork",
    "Update1HYPE!",
    "TyFor25mVisitsOMG!",
    "200kMembersINSANE!",
    "50ThousandsFavorites!!!",
    "ULTIMATEGOJO",
    "BlamSecretValentinesCode",
    "BlamSpotInsaneWeekendCodeMustBeSubbedToWork",
    "ThankYouSoMuch45mVisits",
    "HanminloveSecretCodeMustBeSubbedToWork",
    "SkillTreeRestALPHAReportAnyBugs",
    "ALSUpdateIsCooking",
    "BigUpdateWednesday",
    "BUFF"
}

return codes;
